import { ColourId, ColourInfo } from '../types';

export const COLOURS: Record<ColourId, ColourInfo> = {
  red: {
    id: 'red',
    name: 'Crimson Red',
    hex: '#EF4444',
    gradient: 'from-rose-500 via-red-500 to-red-600',
    lightHex: '#FCA5A5',
    glowHex: 'rgba(239, 68, 68, 0.45)',
    textColor: '#FFFFFF',
    symbol: '●',
    patternType: 'dots',
  },
  orange: {
    id: 'orange',
    name: 'Vibrant Orange',
    hex: '#F97316',
    gradient: 'from-amber-400 via-orange-500 to-orange-600',
    lightHex: '#FDBA74',
    glowHex: 'rgba(249, 115, 22, 0.45)',
    textColor: '#FFFFFF',
    symbol: '▲',
    patternType: 'stripes',
  },
  yellow: {
    id: 'yellow',
    name: 'Solar Yellow',
    hex: '#EAB308',
    gradient: 'from-yellow-300 via-yellow-400 to-amber-500',
    lightHex: '#FEF08A',
    glowHex: 'rgba(234, 179, 8, 0.45)',
    textColor: '#1E293B',
    symbol: '★',
    patternType: 'diamonds',
  },
  green: {
    id: 'green',
    name: 'Emerald Green',
    hex: '#10B981',
    gradient: 'from-emerald-400 via-green-500 to-emerald-600',
    lightHex: '#6EE7B7',
    glowHex: 'rgba(16, 185, 129, 0.45)',
    textColor: '#FFFFFF',
    symbol: '◆',
    patternType: 'grid',
  },
  cyan: {
    id: 'cyan',
    name: 'Aqua Cyan',
    hex: '#06B6D4',
    gradient: 'from-cyan-400 via-cyan-500 to-sky-600',
    lightHex: '#67E8F9',
    glowHex: 'rgba(6, 182, 212, 0.45)',
    textColor: '#FFFFFF',
    symbol: '✦',
    patternType: 'waves',
  },
  blue: {
    id: 'blue',
    name: 'Cobalt Blue',
    hex: '#3B82F6',
    gradient: 'from-blue-400 via-blue-600 to-indigo-700',
    lightHex: '#93C5FD',
    glowHex: 'rgba(59, 130, 246, 0.45)',
    textColor: '#FFFFFF',
    symbol: '■',
    patternType: 'chevrons',
  },
  purple: {
    id: 'purple',
    name: 'Mystic Purple',
    hex: '#8B5CF6',
    gradient: 'from-purple-400 via-purple-600 to-violet-700',
    lightHex: '#C4B5FD',
    glowHex: 'rgba(139, 92, 246, 0.45)',
    textColor: '#FFFFFF',
    symbol: '♠',
    patternType: 'cross',
  },
  pink: {
    id: 'pink',
    name: 'Flamingo Pink',
    hex: '#EC4899',
    gradient: 'from-pink-400 via-pink-500 to-rose-600',
    lightHex: '#F9A8D4',
    glowHex: 'rgba(236, 72, 153, 0.45)',
    textColor: '#FFFFFF',
    symbol: '♥',
    patternType: 'diagonal',
  },
  silver: {
    id: 'silver',
    name: 'Silver Mist',
    hex: '#CBD5E1',
    gradient: 'from-slate-200 via-slate-300 to-zinc-400',
    lightHex: '#F1F5F9',
    glowHex: 'rgba(203, 213, 225, 0.45)',
    textColor: '#0F172A',
    symbol: '○',
    patternType: 'rings',
  },
  teal: {
    id: 'teal',
    name: 'Deep Teal',
    hex: '#14B8A6',
    gradient: 'from-teal-300 via-teal-500 to-cyan-700',
    lightHex: '#5EEAD4',
    glowHex: 'rgba(20, 184, 166, 0.45)',
    textColor: '#FFFFFF',
    symbol: '♣',
    patternType: 'zigzag',
  },
  coral: {
    id: 'coral',
    name: 'Neon Coral',
    hex: '#F43F5E',
    gradient: 'from-rose-400 via-rose-500 to-red-600',
    lightHex: '#FDA4AF',
    glowHex: 'rgba(244, 63, 94, 0.45)',
    textColor: '#FFFFFF',
    symbol: '♦',
    patternType: 'stars',
  },
  amber: {
    id: 'amber',
    name: 'Warm Amber',
    hex: '#D97706',
    gradient: 'from-amber-400 via-amber-600 to-yellow-700',
    lightHex: '#FCD34D',
    glowHex: 'rgba(217, 119, 6, 0.45)',
    textColor: '#FFFFFF',
    symbol: '☼',
    patternType: 'honeycomb',
  },
};

export function getColour(id: ColourId): ColourInfo {
  return COLOURS[id] || COLOURS.red;
}
